### PR TITLE
Upgrade twilio & firebase-admin packages

### PR DESCRIPTION
**Pull request by andrewkhaw**
What does this PR do?
---------------------
<Enter your description>

How can I test this?
--------------------
<Enter instructions for testing/approving PR>

Notes
-----
<Enter notes, remove if not applicable>

### CODE REVIEW

**Comment by Bronsequences** [comment]
Have we tested these changes with our messaging service to ensure push notifications and SMS's still work with these updates?

**Comment by andrewkhaw** [comment]
> Have we tested these changes with our messaging service to ensure push notifications and SMS's still work with these updates?

In the midst of testing it

**Comment by syakiruzair-seekasia** [comment]
Sent 2 SMSes to myself but havent received since then (> 15 minutes). I wonder if its because I am not in Malaysia. I have roaming on though

**Comment by vincentleekp** [comment]
@syakiruzair-seekasia twilio logs can't find your phone number. 
FYI @adrianheng-seekasia testing this.

**Comment by adrianheng-seekasia** [comment]
Tested this out by doing a test deploy of https://github.com/seekinternational/el-messaging-service/, which depends on this library. 

First I pointed my test branch to the commit in this PR and deployed it :
```
  "dependencies": {
...
    "notification-library": "git+https://git@github.com/seekinternational/notification-library.git#45e4cde8f525b48be760df5c06219e0deeca6427"
...
  }
```

I then attempted to send an SMS, and I ran into this syntax error:

screen shot 2018-11-27 at 1 57 47 pm


Logs here: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/el-messaging-service-dev-processMessage;stream=2018/11/27/[$LATEST]58a3e5a911b04feea0453fd7e7057e43;start=2018-11-26T05:57:11Z

Uncertain of the exact root cause at the moment (node versioning, perhaps?), but reverting back to notification-library.git#1.0.2 does not cause the above issue to happen.

**Comment by adrianheng-seekasia** [comment]
As per investigation with @andrewkhaw , this appears to be because https://github.com/seekinternational/el-messaging-service/ is using a very outdated version of notification-library, and one of the releases (1.1.0) in between the version it's using and this PR dropped support for the Node 6 runtime which el-messaging-service uses.

After doing a test deploy with Node 8.10 set as the runtime, there doesn't appear to be any compatibility issues between this PR and el-messaging-service.

**Pull request merged**
